services:
  - type: web
    name: Url Shortener service
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    branch: main
    envVars:
      - key: PORT
        value: 8000
      - key: MONGODB_URI
        sync: false