services:
  - type: web
    runtime: python
    name: url-shortener
    repo: https://github.com/spoo-me/url-shortener
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: MONGODB_URI
      - key: CONTACT_WEBHOOK
      - key: URL_REPORT_WEBHOOK