name: API Test

on:
  push:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest

    env:
      NGROK_URL: ""
      MONGODB_URI: ${{ secrets.MONGODB_URI }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Start Flask server
      run: python main.py &

    - name: Wait for server to start
      run: sleep 10

    - name: Start ngrok
      run: |
        ./ngrok http 8000 > /dev/null 2>&1 &
        sleep 15

    - name: Get ngrok public URL
      run: echo "::set-env name=NGROK_URL::$(curl -s http://localhost:4040/api/tunnels | jq -r .tunnels[0].public_url)"

    - name: Run API test
      run: python tests/shorten.py "${{ env.NGROK_URL }}"
